#ifndef _SRC_CLUCENE_CLUCENE_CONFIG_H
#define _SRC_CLUCENE_CLUCENE_CONFIG_H 1
 
/*
src/CLucene/clucene-config.h.
Generated
automatically
at
end
of
configure.
*/
/* config.h.tmp.  Generated by configure.  */
/* config.h.tmp.in.  Generated from configure.ac by autoheader.  */

/* Disable multithreading */
#ifndef _CL_DISABLE_MULTITHREADING
#cmakedefine _CL_DISABLE_MULTITHREADING  1
#endif

/* Define to 1 if you have the <algorithm> header file. */
#ifndef _CL_HAVE_ALGORITHM 
#cmakedefine _CL_HAVE_ALGORITHM  1
#endif

/* Define to 1 if you have the <ctype.h> header file. */
#ifndef _CL_HAVE_CTYPE_H 
#cmakedefine _CL_HAVE_CTYPE_H  1 
#endif

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#ifndef _CL_HAVE_DIRENT_H 
#cmakedefine _CL_HAVE_DIRENT_H  1 
#endif

/* Define to 1 if you have the <dlfcn.h> header file. */
#ifndef _CL_HAVE_DLFCN_H
#cmakedefine _CL_HAVE_DLFCN_H  1
#endif

/* Define to 1 if you have the <errno.h> header file. */
#ifndef _CL_HAVE_ERRNO_H 
#cmakedefine _CL_HAVE_ERRNO_H  1 
#endif

/* Define to 1 if you have the <ext/hash_map> header file. */
#ifndef _CL_HAVE_EXT_HASH_MAP 
#cmakedefine _CL_HAVE_EXT_HASH_MAP  1 
#endif

/* Define to 1 if you have the <ext/hash_set> header file. */
#ifndef _CL_HAVE_EXT_HASH_SET 
#cmakedefine _CL_HAVE_EXT_HASH_SET  1 
#endif

/* Define to 1 if you have the <fcntl.h> header file. */
#ifndef _CL_HAVE_FCNTL_H 
#cmakedefine _CL_HAVE_FCNTL_H  1 
#endif

/* Define to 1 if the system has the type `float_t'. */
#ifndef _CL_HAVE_FLOAT_T
#cmakedefine _CL_HAVE_FLOAT_T  1
#endif

/* Define to 1 if you have the <functional> header file. */
#ifndef _CL_HAVE_FUNCTIONAL 
#cmakedefine _CL_HAVE_FUNCTIONAL  1 
#endif

/* Does not support new float byte<->float conversions */
#ifndef _CL_HAVE_FUNCTIONING_FLOAT_BYTE 
#cmakedefine _CL_HAVE_FUNCTIONING_FLOAT_BYTE   
#endif

/* Define to 1 if you have the `getpagesize' function. */
#ifndef _CL_HAVE_GETPAGESIZE 
#cmakedefine _CL_HAVE_GETPAGESIZE  1 
#endif

/* Define to 1 if you have the <hash_map> header file. */
#ifndef _CL_HAVE_HASH_MAP
#cmakedefine _CL_HAVE_HASH_MAP  1
#endif

/* Define to 1 if you have the <hash_set> header file. */
#ifndef _CL_HAVE_HASH_SET
#cmakedefine _CL_HAVE_HASH_SET  1
#endif

/* Define to 1 if the system has the type `intptr_t'. */
#ifndef _CL_HAVE_INTPTR_T 
#cmakedefine _CL_HAVE_INTPTR_T  1 
#endif

/* Define to 1 if you have the <inttypes.h> header file. */
#ifndef _CL_HAVE_INTTYPES_H 
#cmakedefine _CL_HAVE_INTTYPES_H  1 
#endif

/* Define to 1 if you have the <list> header file. */
#ifndef _CL_HAVE_LIST 
#cmakedefine _CL_HAVE_LIST  1 
#endif

/* Define to 1 if you have the `lltoa' function. */
#ifndef _CL_HAVE_LLTOA
#cmakedefine _CL_HAVE_LLTOA  1
#endif

/* Define to 1 if you have the `lltow' function. */
#ifndef _CL_HAVE_LLTOW 
#cmakedefine _CL_HAVE_LLTOW  1 
#endif

/* Define to 1 if long double works and has more range or precision than
   double. */
#ifndef _CL_HAVE_LONG_DOUBLE 
#cmakedefine _CL_HAVE_LONG_DOUBLE  1 
#endif

/* Define to 1 if you have the <map> header file. */
#ifndef _CL_HAVE_MAP 
#cmakedefine _CL_HAVE_MAP  1 
#endif

/* Define to 1 if you have the <math.h> header file. */
#ifndef _CL_HAVE_MATH_H 
#cmakedefine _CL_HAVE_MATH_H  1 
#endif

/* Define to 1 if you have the <memory.h> header file. */
#ifndef _CL_HAVE_MEMORY_H 
#cmakedefine _CL_HAVE_MEMORY_H  1 
#endif

/* Define to 1 if you have a working `mmap' system call. */
#ifndef _CL_HAVE_MMAP
#cmakedefine _CL_HAVE_MMAP 1
#endif

/* define if the compiler implements namespaces */
#ifndef _CL_HAVE_NAMESPACES 
#cmakedefine _CL_HAVE_NAMESPACES 1
#endif

/* Define if you have the nanosleep function */
#ifndef _CL_HAVE_NANOSLEEP
#cmakedefine _CL_HAVE_NANOSLEEP  1
#endif

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
#ifndef _CL_HAVE_NDIR_H
#cmakedefine _CL_HAVE_NDIR_H  1
#endif

/* Does not support new float byte<->float conversions */
#ifndef _CL_HAVE_NO_FLOAT_BYTE
#cmakedefine _CL_HAVE_NO_FLOAT_BYTE  1
#endif

/* Does not support try/catch blocks */
#ifndef _CL_HAVE_NO_FUNCTION_TRY_BLOCKS
#cmakedefine _CL_HAVE_NO_FUNCTION_TRY_BLOCKS  1
#endif

/* Define to 1 if you have the `printf' function. */
#ifndef _CL_HAVE_PRINTF 
#cmakedefine _CL_HAVE_PRINTF  1 
#endif

/* Define if you have POSIX threads libraries and header files. */
#ifndef _CL_HAVE_PTHREAD
#cmakedefine _CL_HAVE_PTHREAD  1
#endif

/* Define if recursive pthread mutexes are available */
#ifndef _CL_HAVE_PTHREAD_MUTEX_RECURSIVE
#cmakedefine _CL_HAVE_PTHREAD_MUTEX_RECURSIVE  1
#endif

/* Define to 1 if you have the <set> header file. */
#ifndef _CL_HAVE_SET 
#cmakedefine _CL_HAVE_SET  1 
#endif

/* Define to 1 if you have the `snprintf' function. */
#ifndef _CL_HAVE_SNPRINTF 
#cmakedefine _CL_HAVE_SNPRINTF  1 
#endif

/* Defined if the snprintf overflow test fails */
#ifndef _CL_HAVE_SNPRINTF_BUG
#cmakedefine _CL_HAVE_SNPRINTF_BUG  1
#endif

/* Define to 1 if you have the `snwprintf' function. */
#ifndef _CL_HAVE_SNWPRINTF
#cmakedefine _CL_HAVE_SNWPRINTF  1
#endif

/* define if the compiler supports ISO C++ standard library */
#ifndef _CL_HAVE_STD 
#cmakedefine _CL_HAVE_STD   
#endif

/* Define to 1 if you have the <stdarg.h> header file. */
#ifndef _CL_HAVE_STDARG_H 
#cmakedefine _CL_HAVE_STDARG_H  1 
#endif

/* Define to 1 if you have the <stdexcept> header file. */
#ifndef _CL_HAVE_STDEXCEPT
#cmakedefine _CL_HAVE_STDEXCEPT   
#endif

/* Define to 1 if you have the <stdint.h> header file. */
#ifndef _CL_HAVE_STDINT_H 
#cmakedefine _CL_HAVE_STDINT_H  1 
#endif

/* Define to 1 if you have the <stdlib.h> header file. */
#ifndef _CL_HAVE_STDLIB_H 
#cmakedefine _CL_HAVE_STDLIB_H  1 
#endif

/* define if the compiler supports Standard Template Library */
#ifndef _CL_HAVE_STL 
#cmakedefine _CL_HAVE_STL   
#endif

/* Define to 1 if you have the <strings.h> header file. */
#ifndef _CL_HAVE_STRINGS_H 
#cmakedefine _CL_HAVE_STRINGS_H  1 
#endif

/* Define to 1 if you have the <string.h> header file. */
#ifndef _CL_HAVE_STRING_H 
#cmakedefine _CL_HAVE_STRING_H  1 
#endif

/* Define to 1 if you have the `strlwr' function. */
#ifndef _CL_HAVE_STRLWR
#cmakedefine _CL_HAVE_STRLWR  1
#endif

/* Define to 1 if you have the `strtoll' function. */
#ifndef _CL_HAVE_STRTOLL
#cmakedefine _CL_HAVE_STRTOLL  1
#endif

/* Define to 1 if you have the `strupr' function. */
#ifndef _CL_HAVE_STRUPR
#cmakedefine _CL_HAVE_STRUPR  1
#endif

/* Defined if the swprintf test fails */
#ifndef _CL_HAVE_SWPRINTF_BUG 
#cmakedefine _CL_HAVE_SWPRINTF_BUG 1
#endif

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
#ifndef _CL_HAVE_SYS_DIR_H
#cmakedefine _CL_HAVE_SYS_DIR_H 1
#endif

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
#ifndef _CL_HAVE_SYS_NDIR_H
#cmakedefine _CL_HAVE_SYS_NDIR_H 1
#endif

/* Define to 1 if you have the <sys/stat.h> header file. */
#ifndef _CL_HAVE_SYS_STAT_H 
#cmakedefine _CL_HAVE_SYS_STAT_H  1 
#endif

/* Define to 1 if you have the <sys/timeb.h> header file. */
#ifndef _CL_HAVE_SYS_TIMEB_H 
#cmakedefine _CL_HAVE_SYS_TIMEB_H  1 
#endif

/* Define to 1 if you have the <sys/types.h> header file. */
#ifndef _CL_HAVE_SYS_TYPES_H 
#cmakedefine _CL_HAVE_SYS_TYPES_H  1 
#endif

/* Define to 1 if you have the <tchar.h> header file. */
#ifndef _CL_HAVE_TCHAR_H 
#cmakedefine _CL_HAVE_TCHAR_H  1 
#endif

/* Define to 1 if you have the `tell' function. */
#ifndef _CL_HAVE_TELL 
#cmakedefine _CL_HAVE_TELL  1 
#endif

/* Define to 1 if you have the <unistd.h> header file. */
#ifndef _CL_HAVE_UNISTD_H 
#cmakedefine _CL_HAVE_UNISTD_H  1 
#endif

/* Define to 1 if you have the <vector> header file. */
#ifndef _CL_HAVE_VECTOR 
#cmakedefine _CL_HAVE_VECTOR  1 
#endif

/* Define to 1 if you have the `vsnwprintf' function. */
#ifndef _CL_HAVE_VSNWPRINTF
#cmakedefine _CL_HAVE_VSNWPRINTF  1
#endif

/* Define to 1 if you have the <wchar.h> header file. */
#ifndef _CL_HAVE_WCHAR_H 
#cmakedefine _CL_HAVE_WCHAR_H  1 
#endif

/* Define to 1 if the system has the type `wchar_t'. */
#ifndef _CL_HAVE_WCHAR_T 
#cmakedefine _CL_HAVE_WCHAR_T  1 
#endif

/* Define to 1 if you have the `wcscasecmp' function. */
#ifndef _CL_HAVE_WCSCASECMP
#cmakedefine _CL_HAVE_WCSCASECMP  1
#endif

/* Define to 1 if you have the `wcscat' function. */
#ifndef _CL_HAVE_WCSCAT 
#cmakedefine _CL_HAVE_WCSCAT  1 
#endif

/* Define to 1 if you have the `wcschr' function. */
#ifndef _CL_HAVE_WCSCHR 
#cmakedefine _CL_HAVE_WCSCHR  1 
#endif

/* Define to 1 if you have the `wcscmp' function. */
#ifndef _CL_HAVE_WCSCMP 
#cmakedefine _CL_HAVE_WCSCMP  1 
#endif

/* Define to 1 if you have the `wcscpy' function. */
#ifndef _CL_HAVE_WCSCPY 
#cmakedefine _CL_HAVE_WCSCPY  1 
#endif

/* Define to 1 if you have the `wcscspn' function. */
#ifndef _CL_HAVE_WCSCSPN 
#cmakedefine _CL_HAVE_WCSCSPN  1 
#endif

/* Define to 1 if you have the `wcsicmp' function. */
#ifndef _CL_HAVE_WCSICMP 
#cmakedefine _CL_HAVE_WCSICMP  1 
#endif

/* Define to 1 if you have the `wcslen' function. */
#ifndef _CL_HAVE_WCSLEN 
#cmakedefine _CL_HAVE_WCSLEN  1 
#endif

/* Define to 1 if you have the `wcsncmp' function. */
#ifndef _CL_HAVE_WCSNCMP 
#cmakedefine _CL_HAVE_WCSNCMP  1 
#endif

/* Define to 1 if you have the `wcsncpy' function. */
#ifndef _CL_HAVE_WCSNCPY 
#cmakedefine _CL_HAVE_WCSNCPY  1 
#endif

/* Define to 1 if you have the `wcsstr' function. */
#ifndef _CL_HAVE_WCSSTR 
#cmakedefine _CL_HAVE_WCSSTR  1 
#endif

/* Define to 1 if you have the `wcstod' function. */
#ifndef _CL_HAVE_WCSTOD 
#cmakedefine _CL_HAVE_WCSTOD  1 
#endif

/* Define to 1 if you have the `wcstoll' function. */
#ifndef _CL_HAVE_WCSTOLL 
#cmakedefine _CL_HAVE_WCSTOLL  1 
#endif

/* Define to 1 if you have the `wcsupr' function. */
#ifndef _CL_HAVE_WCSUPR 
#cmakedefine _CL_HAVE_WCSUPR  1 
#endif

/* Define to 1 if you have a functioning <wchar.h> header file. */
#ifndef _CL_HAVE_WCTYPE_H 
#cmakedefine _CL_HAVE_WCTYPE_H   1
#endif

/* Define to 1 if you have the <windows.h> header file. */
#ifndef _CL_HAVE_WINDOWS_H
#cmakedefine _CL_HAVE_WINDOWS_H 1
#endif

#ifdef _CL_HAVE_WINDOWS_H
#define LUCENE_USE_WINDOWS_H  1
#endif

/* Define to 1 if you have the `wprintf' function. */
#ifndef _CL_HAVE_WPRINTF
#cmakedefine _CL_HAVE_WPRINTF  1
#endif

/* Define to 1 if you have the `_filelength' function. */
#ifndef _CL_HAVE__FILELENGTH 
#cmakedefine _CL_HAVE__FILELENGTH  1 
#endif

/* How to define a static const in a class */
#ifndef LUCENE_STATIC_CONSTANT_SYNTAX 
#cmakedefine LUCENE_STATIC_CONSTANT_SYNTAX  1 
#endif

/* Name of package */
#ifndef _CL_PACKAGE 
#cmakedefine _CL_PACKAGE  "clucene-core" 
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef _CL_PACKAGE_BUGREPORT 
#cmakedefine _CL_PACKAGE_BUGREPORT  "" 
#endif

/* Define to the full name of this package. */
#ifndef _CL_PACKAGE_NAME 
#cmakedefine _CL_PACKAGE_NAME  "" 
#endif

/* Define to the full name and version of this package. */
#ifndef _CL_PACKAGE_STRING 
#cmakedefine _CL_PACKAGE_STRING  "" 
#endif

/* Define to the one symbol short name of this package. */
#ifndef _CL_PACKAGE_TARNAME 
#cmakedefine _CL_PACKAGE_TARNAME  "" 
#endif

/* Define to the version of this package. */
#ifndef _CL_PACKAGE_VERSION 
#cmakedefine _CL_PACKAGE_VERSION  "" 
#endif

/* Define to the necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef _CL_PTHREAD_CREATE_JOINABLE */

/* The size of a `unsigned char', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_CHAR */

/* The size of a `unsigned int', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_INT */

/* The size of a `unsigned long', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_LONG */

/* The size of a `unsigned long long', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_LONG_LONG */

/* The size of a `unsigned __int64', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED___INT64 */

/* Define to 1 if the `S_IS*' macros in <sys/stat.h> do not work properly. */
/* #undef _CL_STAT_MACROS_BROKEN */

/* Define to 1 if you have the ANSI C header files. */
#ifndef _CL_STDC_HEADERS 
#cmakedefine _CL_STDC_HEADERS  1 
#endif

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#ifndef _CL_TIME_WITH_SYS_TIME 
#cmakedefine _CL_TIME_WITH_SYS_TIME  1 
#endif

/* Version number of package */
#ifndef _CL_VERSION 
#define _CL_VERSION  "@CLUCENE_VERSION@"
#endif

/* Forces into Ascii mode */
/* #undef _ASCII */

/* Conditional Debugging */
/* #undef _CL__CND_DEBUG */

/* debuging option */
/* #undef _DEBUG */

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* If not already defined, then define as a datatype of *exactly* 32 bits. */
/* #undef uint32_t */

/* If not already defined, then define as a datatype of *exactly* 64 bits. */
/* #undef uint64_t */

/* If not already defined, then define as a datatype of *exactly* 8 bits. */
/* #undef uint8_t */

/* once:
_SRC_CLUCENE_CLUCENE_CONFIG_H
*/
#endif
