# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/blocks/workflow.yml

.tox_base:
  stage: test
  image: python:3.11
  tags:
    - Linux
  interruptible: true
  before_script:
    - python --version
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install tox unittest-xml-reporting
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: JUnit*Results.xml

py39:
  extends: .tox_base
  image: python:3.9
  script: tox -e py39

py310:
  extends: .tox_base
  image: python:3.10
  script: tox -e py310

py311:
  extends: .tox_base
  image: python:3.11
  script: tox -e py311

py312:
  extends: .tox_base
  image: python:3.12
  script: tox -e py312

py313:
  extends: .tox_base
  image: python:3.13
  script: tox -e py313

lint:
  extends: .tox_base
  script: tox -e lint

imports:
  extends: .tox_base
  script: tox -e check-imports

