# set the current version number
set(AUTOMOC4_VERSION_MAJOR  "0")
set(AUTOMOC4_VERSION_MINOR  "9")
set(AUTOMOC4_VERSION_PATCH "89")

set(AUTOMOC4_VERSION "${AUTOMOC4_VERSION_MAJOR}.${AUTOMOC4_VERSION_MINOR}.${AUTOMOC4_VERSION_PATCH}")

